site_name: Documentação Novo SGP
repo_url: https://github.com/prefeiturasp/SME-NovoSGP-Docs
copyright: | 
  &copy; Prefeitura Municipal de São Paulo

extra:
    social:
      - icon: fontawesome/brands/github
        link: https://github.com/prefeiturasp/SME-NovoSGP-Docs

markdown_extensions:
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - admonition
    - pymdownx.arithmatex:
        generic: true
    - pymdownx.details
    - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.mark
    - attr_list
    - pymdownx.tasklist
    - pymdownx.tilde
    - pymdownx.caret
    - pymdownx.mark

theme:
    name: material
    features:
      - navigation.sections
      - navigation.expand
      - navigation.top
      - navigation.footer
    palette:

      # Palette toggle for light mode
       - scheme: default
         primary: teal
         toggle:
           icon: material/weather-night
           name: Modo Escuro

      # Palette toggle for dark mode
       - scheme: slate
         primary: teal
         toggle:
           icon: material/brightness-7
           name: Modo Claro
    language: pt-BR