site_name: Documentação Novo SGP
repo_url: https://github.com/prefeiturasp/SME-NovoSGP
copyright: | 
  &copy; Prefeitura Municipal de São Paulo

nav:
  - Início: index.md
  - Permissionamento: Permissionamento/permissionamento.md
  - WorkerSGP: 
    - Visão Geral: WorkerSGP/workersgp.md
    - DeadLetters: WorkerSGP/deadletter.md
  - Monitoramento: 
    - Visão Geral: Monitoramento/monitoramento.md
    - Logs: Monitoramento/logs.md
    - Performance: Monitoramento/performance.md
  - Docker & Tilt: docker_tilt.md
  - Integrações:
    - API EOL: 
      - O que é: Integracoes/EOL/apieol.md
      - Configuração: Integracoes/EOL/apieolsecret.md
    - API Jurema:
      - O que é: Integracoes/Jurema/jurema.md
      - Configuração: Integracoes/Jurema/juremasecret.md
    - Escola Aqui:
      - O que é ?: Integracoes/AE/ae.md
      - Configuração: Integracoes/AE/aesecret.md
    - Servidor de Relatórios:
      - Para que serve ?: Integracoes/ServidorRelatorios/servidorrelatorios.md
      - Configuração: Integracoes/ServidorRelatorios/servidorrelatoriossecret.md
    - Jasper Reports:
      - O que é ?: Integracoes/JasperReports/jasper.md
      - Configuração: Integracoes/JasperReports/jaspersecret.md
    - RabbitMQ:
      - O que é ?: Integracoes/RabbitMQ/rabbit.md
      - Configuração: Integracoes/RabbitMQ/rabbitsecret.md
    - MinIO:
      - O que é ?: Integracoes/MinIO/minio.md
      - Configuração: Integracoes/MinIO/miniosecret.md
    - Redis:
      - O que é ?: Integracoes/Redis/redis.md
      - Configuração: Integracoes/Redis/redissecret.md
    - ElasticSearch:
      - O que é ?: Integracoes/ElasticSearch/elasticsearch.md
      - Configuração: Integracoes/ElasticSearch/elasticsearchsecret.md
    - APM:
      - O que é ?: Integracoes/APM/apm.md
      - Configuração: Integracoes/APM/apmsecret.md
    - GitHub:
      - Para que serve ?: Integracoes/Github/github.md
      - Configuração: Integracoes/Github/githubsecret.md

extra:
    social:
      - icon: fontawesome/brands/github
        link: https://github.com/prefeiturasp/SME-NovoSGP

extra_css:
  - css/style.css

markdown_extensions:
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - admonition
    - pymdownx.arithmatex:
        generic: true
    - pymdownx.details
    - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.mark
    - attr_list
    - pymdownx.tasklist
    - pymdownx.tilde
    - pymdownx.caret
    - pymdownx.mark

theme:
    name: material
    features:
      - navigation.sections
      - navigation.expand
      - navigation.top
      - navigation.footer
      - navigation.instant
    palette:

      # Palette toggle for light mode
       - scheme: default
         primary: teal
         toggle:
           icon: material/weather-night
           name: Modo Escuro

      # Palette toggle for dark mode
       - scheme: slate
         primary: teal
         toggle:
           icon: material/brightness-7
           name: Modo Claro
    language: pt-BR